# Generated by Django 6.0.1 on 2026-02-04 21:35

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_comment_created_at_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[api.validators.validate_profile_image]),
        ),
    ]
